export const data = {
  'Item_Weapon_AK47_C': 'AKM',
  'Item_Weapon_AUG_C': 'AUG A3',
  'Item_Weapon_AWM_C': 'AWM',
  'Item_Weapon_Berreta686_C': 'S686',
  'Item_Weapon_BerylM762_C': 'Beryl',
  'Item_Weapon_BizonPP19_C': 'Bizon',
  'Item_Weapon_Cowbar_C': 'Crowbar',
  'Item_Weapon_Crossbow_C': 'Crossbow',
  'Item_Weapon_DP28_C': 'DP-28',
  'Item_Weapon_FlareGun_C': 'Flare Gun',
  'Item_Weapon_FlashBang_C': 'Flashbang',
  'Item_Weapon_FNFal_C': 'SLR',
  'Item_Weapon_G18_C': 'P18C',
  'Item_Weapon_G36C_C': 'G36C',
  'Item_Weapon_Grenade_C': 'Frag Grenade',
  'Item_Weapon_Groza_C': 'Groza',
  'Item_Weapon_HK416_C': 'M416',
  'Item_Weapon_Kar98k_C': 'Kar98k',
  'Item_Weapon_M16A4_C': 'M16A4',
  'Item_Weapon_M1911_C': 'P1911',
  'Item_Weapon_M249_C': 'M249',
  'Item_Weapon_M24_C': 'M24',
  'Item_Weapon_M9_C': 'P92',
  'Item_Weapon_Machete_C': 'Machete',
  'Item_Weapon_Mini14_C': 'Mini 14',
  'Item_Weapon_Mk14_C': 'Mk14 EBR',
  'Item_Weapon_Mk47Mutant_C': 'Mk47 Mutant',
  'Item_Weapon_Molotov_C': 'Molotov Cocktail',
  'Item_Weapon_MP5K_C': 'MP5K',
  'Item_Weapon_NagantM1895_C': 'R1895',
  'Item_Weapon_Pan_C': 'Pan',
  'Item_Weapon_QBU88_C': 'QBU88',
  'Item_Weapon_QBZ95_C': 'QBZ95',
  'Item_Weapon_Rhino_C': 'R45',
  'Item_Weapon_Saiga12_C': 'S12K',
  'Item_Weapon_Sawnoff_C': 'Sawed-off',
  'Item_Weapon_SCAR-L_C': 'SCAR-L',
  'Item_Weapon_Sickle_C': 'Sickle',
  'Item_Weapon_SKS_C': 'SKS',
  'Item_Weapon_SmokeBomb_C': 'Smoke Grenade',
  'Item_Weapon_Thompson_C': 'Tommy Gun',
  'Item_Weapon_UMP_C': 'UMP9',
  'Item_Weapon_UZI_C': 'Micro Uzi',
  'Item_Weapon_Vector_C': 'Vector',
  'Item_Weapon_VSS_C': 'VSS',
  'Item_Weapon_vz61Skorpion_C': 'Skorpion',
  'Item_Weapon_Win1894_C': 'Win94',
  'Item_Weapon_Winchester_C': 'S1897',
};

export const weapons = Object.keys(data).map(key => {
  return {
    uri: key,
    name: data[key],
  };
});
